name: publish-pypi

on:
  release:
    types:
      - published

jobs:
  publish-pypi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Prepare
        run: |
          pip install -U pip wheel
      - env:
          PACKAGE_VERSION: ${{ github.head_ref || github.ref_name }}
        name: Build package
        run: |
          python setup.py sdist bdist_wheel
      - name: Publish PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
